version: "3.7"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $POSTPASS
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_notes
    volumes:
    - ./volumes/postgres:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
    - "81:8080"
