version: "3.7"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $POSTPASS
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_notes
    volumes:
    - ./volumes/postgres:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zsazu.com
      PGADMIN_DEFAULT_PASSWORD: $PGPASS
    ports:
    - "5050:80"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
    - "81:8080"
  web:
    build:
      context: ./web
    ports:
    - "80:4173"