# build SERVER
FROM node:16 AS builder
WORKDIR /usr/src/server
COPY package*.json ./
RUN npm ci && npm install typescript -g
COPY . .
RUN npm run build

FROM node:16.17.0-bullseye-slim
WORKDIR /usr/src/server
COPY package*.json ./
RUN npm ci
COPY --from=builder /usr/src/server/dist ./dist
EXPOSE 8080
CMD ["node", "dist/index.js"]